// GENERATED by tool/gen_abi.dart — do NOT edit by hand.
// Regenerate: dart run tool/gen_abi.dart
//
// Byte offsets are mirrored from the C++ COMMAND_EXPORT_ABI_OFFSET locks,
// which the compiler verifies against the real struct layout.
// Sources:
//   vendor/maplibre-native/include/mbgl/command_export/draw_command.hpp (DrawCommand)
//   native/bridge_labels.cpp (LabelExport)

/// Byte offsets of C++ `DrawCommand` (size 400).
class DrawCommandAbi {
  DrawCommandAbi._();
  static const int size = 400;
  static const int shaderType = 0;
  static const int drawMode = 4;
  static const int vertexData = 8;
  static const int vertexCount = 16;
  static const int vertexStride = 20;
  static const int indexData = 24;
  static const int indexCount = 32;
  static const int flags = 36;
  static const int drawableUBO = 40;
  static const int drawableUBOSize = 168;
  static const int propsUBO = 172;
  static const int propsUBOSize = 268;
  static const int layerIndex = 272;
  static const int bufferId = 276;
  static const int bufferVersion = 280;
  static const int texChannels = 284;
  static const int texData = 288;
  static const int texWidth = 296;
  static const int texHeight = 300;
  static const int texId = 304;
  static const int texVersion = 308;
  static const int tilePropsUBO = 312;
  static const int tilePropsUBOSize = 376;
  static const int cameraDistance = 380;
  static const int texFilter = 384;
  static const int subLayerIndex = 388;
  static const int stencilReference = 392;
  static const int stencilMode = 396;
}

/// Byte offsets of C++ `LabelExport` (size 400).
class LabelExportAbi {
  LabelExportAbi._();
  static const int size = 400;
  static const int lat = 0;
  static const int lon = 8;
  static const int iconLat = 16;
  static const int iconLon = 24;
  static const int fontSize = 32;
  static const int textR = 36;
  static const int textG = 40;
  static const int textB = 44;
  static const int textA = 48;
  static const int haloR = 52;
  static const int haloG = 56;
  static const int haloB = 60;
  static const int haloA = 64;
  static const int haloWidth = 68;
  static const int textW = 72;
  static const int textH = 76;
  static const int iconW = 80;
  static const int iconH = 84;
  static const int iconSize = 88;
  static const int iconOpacity = 92;
  static const int iconR = 96;
  static const int iconG = 100;
  static const int iconB = 104;
  static const int iconA = 108;
  static const int flags = 112;
  static const int textAngle = 116;
  static const int crossTileID = 120;
  static const int text = 124;
  static const int layer = 252;
  static const int icon = 316;
  static const int textOffsetX = 380;
  static const int textOffsetY = 384;
  static const int iconOffsetX = 388;
  static const int iconOffsetY = 392;
}
